"""Ajout colonnes a paiement modele

Revision ID: 25518d6cf547
Revises: 
Create Date: 2026-04-28 11:23:00.187234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25518d6cf547'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('annule_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('annule_par', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('motif_annulation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_column('motif_annulation')
        batch_op.drop_column('annule_par')
        batch_op.drop_column('annule_le')
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
