"""nouvelle colonne dans model eleve

Revision ID: 963f29c6cb46
Revises: 
Create Date: 2026-05-18 15:18:12.072390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963f29c6cb46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('observation', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('nom_parent1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profession_parent1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('employeur2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telephone_parent2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('adresse1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('affiliation1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('observation1', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.drop_column('observation1')
        batch_op.drop_column('affiliation1')
        batch_op.drop_column('adresse1')
        batch_op.drop_column('telephone_parent2')
        batch_op.drop_column('employeur2')
        batch_op.drop_column('profession_parent1')
        batch_op.drop_column('nom_parent1')
        batch_op.drop_column('observation')
        batch_op.drop_column('affiliation')

    # ### end Alembic commands ###
